import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <h1><Link href="/">FrontMusics</Link></h1>
        <p>
          <Link href="/estilos/">Estilos musicais</Link> | &nbsp;
          <Link href="/bandas/">Bandas</Link> | &nbsp;
          <Link href="/albuns/">Álbuns</Link>
        </p>
        {children}
      </body>
    </html>
  );
}
